/* C File that stores the main function for graph processing 
   Programmer: Stefan
   Code Tester: Martin and Stefan
*/
#include <stdio.h>
#include <string.h>
#include "sort.h"
#include "helpers.h"

// Typedef declaration of custom string types to be used
typedef char vertex[9];
typedef char string[25];

// Handles the processing for the "*-SET.TXT" file
void ProduceOutputFile1(string outFileName, vertex adj[20][20], int vCount){

	FILE* ptr;
	int maxEdges;
	int cnt = 0; // Counter
	int edgeCount = 0; // Track how many edges are currently in the array

	ptr = fopen(outFileName, "w"); // Opens in write mode
	
	fprintf(ptr, "V(%c)={", outFileName[0]);

	for(int i = 0; i < vCount; i++)
		fprintf(ptr, "%s,", adj[i][0]);

	// Moves the cursor back by 1 space to overwrite the extra ',' character after loop has completed.
	fseek(ptr, -1, SEEK_CUR); 
	fprintf(ptr, "}\n");
	
	// Calculates the size of the edges array using the formula for a complete undirected graph
	maxEdges = vCount * (vCount-1) / 2;


	string edges[maxEdges];// Store all possible edges that can be generated by vertices
	vertex first[maxEdges]; // Store the first half of all possible edges that can be generated by vertices
	vertex second[maxEdges]; // Store the second half of all possible edges that can be generated by vertices
	string temp = "(";

	for(int i = 0; i < vCount; i++){

		for(int j = 1; j < vCount; j++){

			if(strcmp(adj[i][j], "\0")){

				// Checks if the edge already exists within the array
				if(checkEdge(adj[i][0], adj[i][j], first, second, maxEdges)){ 

					edgeCount++;
					
					strcpy(first[cnt],adj[i][0]); // Stores copy of the first half of the edge for later comparison
					strcpy(second[cnt],adj[i][j]); // Stores copy of the second half of the edge for later comparison
					
					strcat(temp,adj[i][0]); // Formats the two parts of the edge into one string before copying into the edges array
					strcat(temp,",");
					strcat(temp,adj[i][j]);
					strcat(temp,"),");
					
					strcpy(edges[cnt],temp);
					
					cnt++;

				}

				reformat(temp); //reformats the temp string
			}
		}
	}

	fprintf(ptr, "E(%c)={", outFileName[0]);
	
	for(int i = 0; i < edgeCount; i++)
		if(strcmp(edges[i], "\0"))
			fprintf(ptr, "%s", edges[i]);
	
	if(edgeCount)
		fseek(ptr,-1,SEEK_CUR); //Moves the cursor back by 1 space to overwrite the extra ',' character after loop has completed.
	
	fprintf(ptr, "}");
	fclose(ptr);

}

// Handles the processing for the "*-DEGREE.TXT" file
void ProduceOutputFile2(string outFileName, vertex adj[20][20], int vCount){

	FILE* ptr;
	ptr = fopen(outFileName, "w"); // Opens in write mode
	
	for(int i = 0; i < vCount; i++){

		int dCount = 0;

		for(int j = 1; j < vCount; j++)
			if(strcmp(adj[i][j],"\0")) //Checks whether element is empty 
				dCount++;
		
		fprintf(ptr,"%s %d\n", adj[i][0],dCount);
	}

	fclose(ptr);

}

// Handles the processing for the "*-LIST.TXT" file
void ProduceOutputFile3(string outFileName, vertex adj[20][20],int vCount){

	FILE* ptr;
	ptr = fopen(outFileName, "w");
	
	for(int i = 0; i < vCount; i++){

		for(int j = 0; j < vCount; j++)
			if(strcmp(adj[i][j], "\0"))
				fprintf(ptr,"%s->", adj[i][j]);
		
		fprintf(ptr, "\\\n");

	}

	fclose(ptr);

}

//Handles the processing for the "*-MATRIX.TXT" file
void ProduceOutputFile4(string outFileName, vertex adj[20][20], int vCount, int adj2[20][20]){
	FILE* ptr;
	ptr=fopen(outFileName, "w");
	
	//Initializes the 2d int matrix into all zeroes
	for(int i=0; i<vCount; i++){
		for(int j=0; j<vCount; j++)
			adj2[i][j]=0;
	}
	
	vertex comp[vCount];
	//Copies the vertex IDs into a 1D array to be used for comparing
	for(int i=0; i<vCount; i++)
		strcpy(comp[i],adj[i][0]);
	/*
	Triple nested for loop for populating the the adjacency matrix.
	First loop iterates through the 1D comp matrix 
	Second loop iterates through the rows/vertices of the matrix/graph
	Third loop iterates through the edges of the current vertex
	*/
	for(int i=0; i<vCount; i++){
		for(int j=0; j<vCount; j++){
			for(int k=0; k<vCount; k++){
				if(strcmp(adj[j][k],comp[i])==0) 
					adj2[j][i]=1;				 
			}
		}
	}
	
	fprintf(ptr,"    ");
	for(int i=0; i<vCount; i++)
		fprintf(ptr,"%s ",comp[i]);
	fprintf(ptr,"\n");
		
	for(int i=0;i<vCount;i++){
		adj2[i][i]=0; //wipes the false positives generated when the ID's were compared to the vertices and not the edges
		fprintf(ptr,"%s ",adj[i][0]);
		for(int j=0;j<vCount;j++){
			fprintf(ptr,"%d ", adj2[i][j]);
		}
		fprintf(ptr,"\n");
	}
	fclose(ptr);
}

//Handles the processing for the "*-BFS.TXT" file
int ProduceOutputFile5(string outFileName, vertex adj[20][20], int vCount, int adj2[20][20]){
	FILE* ptr;
	
	vertex key;
	int index=-1; //int to store index of the chosen starting vertex to be passed on to DFS, assumed false
	
	printf("Input start vertex for the traversal: ");
	scanf("%s", key);
	
	for(int i=0; i<vCount; i++)	//for loop to locate the index of the starting index
		if(strcmp(key,adj[i][0])==0)
			index=i;

	if(index>-1){
		ptr=fopen(outFileName, "w"); 
		
		int visited[vCount];
		int queue[vCount];
	
		for(int i=0; i<vCount; i++){ //initializing arrays to track the vertices that have already been visited/marked
			visited[i]=0; //array to track vertices that have been visited
			queue[i]=-1;  //array to track vertices that have yet to be visited, initialized as -1 since this stores array indexes
		}
		 	
		BFS(adj, adj2, visited, queue, index, vCount, 1);
		
		for(int i=0; i<vCount; i++) //prints out the sequence in which vertices were visited
			if(queue[i]!=-1) //checker to insure it doesn't print values outside of the array
				fprintf(ptr,"%s ", adj[queue[i]][0]);
		
		fclose(ptr);
		return index; //returns the index of the chosen vertex to be passed on to DFS
	}
	else{ //if the starting vertex does not exist within the graph, forego opening/creating a file altogether and end the function
		printf("Vertex %s not found", key);
		return -1;
	}
}

//Handles the processing for the "*-DFS.TXT" file
void ProduceOutputFile6(string outFileName, vertex adj[20][20], int vCount, int index, int adj2[20][20]){
	FILE* ptr;
	ptr=fopen(outFileName, "w");
	
	int visited[vCount];
	
	for(int i=0; i<vCount; i++) //initializing an array to track the vertices that have already been visited/marked
		visited[i]=0;
		
	DFS(ptr,visited,adj,index,adj2,vCount);
	
	fclose(ptr);
}



